name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to AWS ECR
        run: echo "${{ secrets.AWS_ACCESS_KEY_ID }}" | docker login -u AWS --password-stdin <aws_account_id>.dkr.ecr.<region>.amazonaws.com

      - name: Build and push Docker image
        run: |
          docker build -t <image_name>:latest .
          docker tag <image_name>:latest <aws_account_id>.dkr.ecr.<region>.amazonaws.com/<repository_name>:latest
          docker push <aws_account_id>.dkr.ecr.<region>.amazonaws.com/<repository_name>:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull <aws_account_id>.dkr.ecr.<region>.amazonaws.com/<repository_name>:latest
            docker-compose up -d

