name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to AWS ECR
        run: echo "${{ secrets.AWS_ACCESS_KEY_ID }}" | docker login -u AWS --password-stdin 851725531288.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and push Docker image
        run: |
          docker build -t cloud-practice:latest .
          docker tag cloud-practice:latest 851725531288.dkr.ecr.us-east-1.amazonaws.com/cloud-practice:latest
          docker push 851725531288.dkr.ecr.us-east-1.amazonaws.com/cloud-practice:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull 851725531288.dkr.ecr.us-east-1.amazonaws.com/cloud-practice:latest
            docker-compose up -d

